<a href="https://colab.research.google.com/github/rainforest01-coder/ESAA_files/blob/main/ESAA_WEEK01_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##판다스 시작

In [ ]:
import pandas as pd

In [ ]:
titanic_df=pd.read_csv('titanic_train.csv')
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

In [ ]:
print('titanic 변수 type:',type(titanic_df))
titanic_df

titanic 변수 type: <class 'pandas.core.frame.DataFrame'>

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
print('DataFrame의 크기: ', titanic_df.shape)

DataFrame의 크기:  (891, 12)

In [ ]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
titanic_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
titanic_df['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [ ]:
titanic_pclass=titanic_df['Pclass']
print(type(titanic_pclass))

<class 'pandas.core.series.Series'>

In [ ]:
titanic_pclass.head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [ ]:
value_counts  = titanic_df['Pclass'].value_counts()
print(type(value_counts))
print(value_counts)

<class 'pandas.core.series.Series'>
Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [ ]:
print('titanic_df데이터 건수',titanic_df.shape[0])
print('기본 설정인 dropna=True로 value_counts()')
print(titanic_df['Embarked'].value_counts())
print(titanic_df['Embarked'].value_counts(dropna=False))

titanic_df데이터 건수 891
기본 설정인 dropna=True로 value_counts()
Embarked
S    644
C    168
Q     77
Name: count, dtype: int64
Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

##DataFrame과 리스트, 딕셔너리, 넘파이 ndarray 상호 변환

In [ ]:
import numpy as np
col_name1=['col1']
list1=[1,2,3]
array1=np.array(list1)
array1=np.array(list1)
print('array1 shape:',array1.shape)
df_list1=pd.DataFrame(list1,columns=col_name1)
print('1차원 리스트로 만든 DataFrame:\n',df_list1)
df_array1=pd.DataFrame(array1,columns=col_name1)
print('1차원 ndarray로 만든 DataFrame:\n',df_array1)

array1 shape: (3,)
1차원 리스트로 만든 DataFrame:
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame:
    col1
0     1
1     2
2     3

In [ ]:
col_name2=['col1','col2','col3']
list2=[[1,2,3],[11,12,13]]
array2=np.array(list2)
df_list2=pd.DataFrame(list2,columns=col_name2)
print('2차원 리스트로 만든 DataFrame:\n',df_list2)
df_array2=pd.DataFrame(array2,columns=col_name2)
print('2차원 ndarray로 만든 DataFrame:\n',df_array2)

2차원 리스트로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13

In [ ]:
import numpy as np

In [ ]:
dict={'col1':[1,11],'col2':[2,22],'col3':[3,33]}
df_dict=pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame:\n',df_dict)

딕셔너리로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    22    33

In [ ]:
array3=df_dict.values
print('df_dict.values타입',type(array3),'df_dict.values shape:',array3.shape)
print(array3)

df_dict.values타입 <class 'numpy.ndarray'> df_dict.values shape: (2, 3)
[[ 1  2  3]
 [11 22 33]]

In [ ]:
list3=df_dict.values.tolist()
print(type(list3))
list3

<class 'list'>

[[1, 2, 3], [11, 22, 33]]

In [ ]:
dict3=df_dict.to_dict('list')#리스트 형으로 반환
print(type(dict3))
dict3

<class 'dict'>

{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}

##DataFrame의 칼럼 데이터 세트 생성과 수정

In [ ]:
titanic_df['Age_0']=0
titanic_df['Family_No']=titanic_df['SibSp']+titanic_df['Parch']+1
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,1

In [ ]:
titanic_df['Age_by_10']=titanic_df['Age']*10
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Family_No,Age_by_10
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,2,220.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,2,380.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,1,260.0

In [ ]:
titanic_df['Age_by_10']=titanic_df['Age_by_10']+100
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Family_No,Age_by_10
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,2,320.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,2,480.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,1,360.0

###DataFrame 데이터 삭제

DataFrame.drop(**labels=None**, **axis=0**, index=None, colunms=None, level=None, **inplace=False**, errors='raise')
* axis=0: 행 제거, axis=1: 열 제거

In [ ]:
titanic_drop_df=titanic_df.drop(['Age_0'],axis=1)
titanic_drop_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_No,Age_by_10
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,320.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,480.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,360.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,450.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1,450.0

titanic_df는 변화 없음  
inplace=True로 설정하면 자신의 DataFrame의 데이터 삭제  
여러 칼럼을 삭제-> 리스트 형태로 칼럼 명 입력

In [ ]:
drop_result=titanic_df.drop(['Age_0','Age_by_10','Family_No'],axis=1,inplace=True)
print('inplace=True로 drop 후 반환된 값:',drop_result)
titanic_df.head(3)

inplace=True로 drop 후 반환된 값: None

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [ ]:
pd.set_option('display.width',1000)
pd.set_option('display.max_colwidth',15)
print('###before axis 0 drop###')
print(titanic_df.head(3))
titanic_df.drop([0,1,2],axis=0,inplace=True) #반환값이 None이므로 다시 DataFrame에 할당하지 않도록 주의
print('###after axis 0 drop###')
print(titanic_df.head(3))

###before axis 0 drop###
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
###after axis 0 drop###
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q

##index객체

In [ ]:
titanic_df=pd.read_csv('titanic_train.csv')
indexes=titanic_df.index
print(indexes)
print('Index객체 array값:\n',indexes.values)

RangeIndex(start=0, stop=891, step=1)
Index객체 array값:
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521
 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539
 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557
 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575
 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593
 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629
 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647
 648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665
 666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683
 684 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701
 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719
 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737
 738 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755
 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773
 774 775 776 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791
 792 793 794 795 796 797 798 799 800 801 802 803 804 805 806 807 808 809
 810 811 812 813 814 815 816 817 818 819 820 821 822 823 824 825 826 827
 828 829 830 831 832 833 834 835 836 837 838 839 840 841 842 843 844 845
 846 847 848 849 850 851 852 853 854 855 856 857 858 859 860 861 862 863
 864 865 866 867 868 869 870 871 872 873 874 875 876 877 878 879 880 881
 882 883 884 885 886 887 888 889 890]

index객체는 식별성 데이터를 1차원 array로 갖고있음  
ndarray와 유사하게 단일 값 반환 및 슬라이싱 가능

In [ ]:
print(type(indexes.values))
print(indexes.values.shape)
print(indexes.values[:5])
print(indexes[:5].values)
print(indexes.values[6])

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6

한번 만들어진 index객체는 함부로 변경 불가

In [ ]:
#인덱스는 연산에서 제외
series_fair=titanic_df['Fare']
print('Fair Series max 값:',series_fair.max())
print('Fair Series sum 값:',series_fair.sum())
print('sum() Fair Series:',sum(series_fair))
print('Fair Series +3:',(series_fair+3).head(3))

Fair Series max 값: 512.3292
Fair Series sum 값: 28693.9493
sum() Fair Series: 28693.9493
Fair Series +3: 0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64

###reset_index()

인덱스가 연속된 int 숫자형 데이터가 아닐 경우에 다시 이를 연속 int 숫자형 데이터로 만들 때 사용

In [ ]:
titanic_reset_df=titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)

,index,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [ ]:
print('###before reset_index###')
value_counts=titanic_df['Pclass'].value_counts()
print('value_counts')
print(value_counts)
print('###after reset_index###')
new_value_counts=value_counts.reset_index(inplace=False)
print('new_value_counts')
print(new_value_counts)

###before reset_index###
value_counts
Pclass
3    491
1    216
2    184
Name: count, dtype: int64
###after reset_index###
new_value_counts
   Pclass  count
0       3    491
1       1    216
2       2    184

##데이터 셀렉션 및 필터링

###DataFrame의 []연산자

현재 수준에서 칼럼 지정 연산자로 이해하는 것이 좋음  
여러 칼럼은 리스트 객체 이용하여 지정


유의사항  
* 넘파이의 [], Series의 []와 다름  
* 칼럼명 지정 연산이나 불린 인덱스 정도로만 사용
* 슬라이싱 사용 비추

In [ ]:
print('단일 칼럼 데이터 추출:\n',titanic_df['Pclass'].head(3))
print('\n여러 칼럼 데이터 추출:\n',titanic_df[['Survived','Pclass']].head(3))
print('[]안에 있는 숫자 인덱스는 keyerror오류 발생:\n',titanic_df[0])

단일 칼럼 데이터 추출:
 0    3
1    1
2    3
Name: Pclass, dtype: int64

여러 칼럼 데이터 추출:
    Survived  Pclass
0         0       3
1         1       1
2         1       3

KeyError: 0

판다스의 인덱스 형태로 변환 가능한 표현식은 []내 입력 가능

In [ ]:
titanic_df[0:2]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

불린 인덱싱 가능

In [ ]:
titanic_df[titanic_df['Pclass']==3].head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.250,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.925,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.050,NaN,S

###DataFrame iloc연산자

위치기반 인덱싱(행과 열의 위치)  
0을 출발점으로 하는 세로축, 가로축 좌표 정숫값으로 지정

In [ ]:
data={'Name':['Chulmin','Eunkyung','Jinwoong','Soobeom'],'Year':[2011,2016,2015,2015],'Gender':['Male','Female','Male','Female']}
data_df=pd.DataFrame(data,index=['one','two','three','four'])
data_df

           Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015  Female

In [ ]:
print(data_df.iloc[0,0])
print(data_df.iloc[0,'Name']) #열 위치에 정숫값이 아닌 칼럼명을 입력하여 오류 발생

Chulmin

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

####iloc 연산 유형

df.iloc[1,0]: 두번째행 첫번째 열의 단일 값 반환  
df.iloc[0:2,[0,1]] 0:2 슬라이싱 범위의 1,2행과 1,2열에 해당하는 DF반환  
df.iloc[:], df.iloc[:,:] 전체 DF반환

In [ ]:
data_df.iloc[0:2,0:3]

         Name  Year  Gender
one   Chulmin  2011    Male
two  Eunkyung  2016  Female

iloc[:,-1] 맨 마지막 칼럼의 값  
iloc[:,:-1] 맨 마지막 칼럼을 제외한 모든 칼럼의 값

In [ ]:
print('맨 마지막 칼럼 데이터[:,-1]:\n',data_df.iloc[:,-1])
print('맨 마지막 칼럼을 제외한 모든 데이터[:,-1]:\n',data_df.iloc[:,:-1])

맨 마지막 칼럼 데이터[:,-1]:
 one        Male
two      Female
three      Male
four     Female
Name: Gender, dtype: object
맨 마지막 칼럼을 제외한 모든 데이터[:,-1]:
            Name  Year
one     Chulmin  2011
two    Eunkyung  2016
three  Jinwoong  2015
four    Soobeom  2015

###DataFrame의 loc연산자

명칭 기반 인덱싱  
데이터 프레임의 인덱스 값으로 행 위치를, 칼럼 명칭으로 열 위치를 지정하는 방식

In [ ]:
data_df.loc['one','Name']

'Chulmin'

In [ ]:
data_df.loc[0,'Name']

KeyError: 0

슬라이싱 주의사항

시작값:종료값 지정시 **종료값까지 포함**

In [ ]:
print('위치기반:\n',data_df.iloc[0:1,0])
print('명칭기반:\n',data_df.loc['one':'two','Name'])

위치기반:
 one    Chulmin
Name: Name, dtype: object
명칭기반:
 one     Chulmin
two    Eunkyung
Name: Name, dtype: object

####loc[]연산 유형

df.loc['three','Name'] 인덱스 값 three행 Name 칼럼의 단일값 반환  
df.loc['one':'two',['Name','Year']] 인덱스 값 one부터 two행의 Name,Year칼럼에 해당하는 DF 반환  
df.loc[:] 모든 데이터 값  
df.loc[df.Year>=2014] **loc은 불린 인덱싱 가능** Year칼럼의 값이 2014 이상인 데이터를 불린 인덱싱으로 추출

####불린 인덱싱

In [ ]:
titanic_boolean=titanic_df[titanic_df['Age']>60]
print(type(titanic_boolean))
titanic_boolean.head(3)

<class 'pandas.core.frame.DataFrame'>

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C

60세 이상인 승객의 나이와 이름만 추출

In [ ]:
titanic_df[titanic_df['Age']>60][['Name','Age']].head(3)

                              Name   Age
33           Wheadon, Mr. Edward H  66.0
54  Ostby, Mr. Engelhart Cornelius  65.0
96       Goldschmidt, Mr. George B  71.0

loc에서도 동일하게 적용 가능하나 ['Name','Age']는 칼럼 위치에 놓여야 함

In [ ]:
titanic_df.loc[titanic_df['Age']>60,['Name','Age']].head(3)

                              Name   Age
33           Wheadon, Mr. Edward H  66.0
54  Ostby, Mr. Engelhart Cornelius  65.0
96       Goldschmidt, Mr. George B  71.0

여러개의 복합 조건 결합 적용  
* and조건일 경우 &
* or 조건일 경우 |
* not 조건일 경우 ~

In [ ]:
titanic_df[(titanic_df['Age']>60) & (titanic_df['Pclass']==1) & (titanic_df['Sex']=='female')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
275,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN

In [ ]:
cond1=titanic_df['Age']>60
cond2=titanic_df['Pclass']==1
cond3=titanic_df['Sex']=='female'
titanic_df[cond1&cond2&cond3]

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583    D7        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   B28      NaN

##정렬,Aggregation함수,Groupby적용


###DataFrame, Series의 정렬 - sort_values()

by=['특정 칼럼']입력하여 해당 칼럼으로 정렬 수행  
ascending=True 오름차순 / ascending=False 내림차순  
inplace=True 설정하면 DF에 정렬 결과 적용

In [ ]:
titanic_sorted=titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket   Fare Cabin Embarked
845          846         0       3  Abbing, Mr....    male  42.0      0      0  C.A. 5547   7.55   NaN        S
746          747         0       3  Abbott, Mr....    male  16.0      1      1  C.A. 2673  20.25   NaN        S
279          280         1       3  Abbott, Mrs...  female  35.0      1      1  C.A. 2673  20.25   NaN        S

In [ ]:
titanic_sorted=titanic_df.sort_values(by=['Pclass','Name'],ascending=False)
titanic_sorted.head(3)

     PassengerId  Survived  Pclass            Name   Sex   Age  SibSp  Parch    Ticket  Fare Cabin Embarked
868          869         0       3  van Melkebe...  male   NaN      0      0    345777   9.5   NaN        S
153          154         0       3  van Billiar...  male  40.5      0      2  A/5. 851  14.5   NaN        S
282          283         0       3  de Pelsmaek...  male  16.0      0      0    345778   9.5   NaN        S

DF에 aggregation호출할 경우 모든 칼럼에 적용

In [ ]:
titanic_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

특정 칼럼에 적용하기 위해서는 DF에 대상 칼럼들만 추출해 적용

In [ ]:
titanic_df[['Age','Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

####groupby() 적용

by='칼럼'입력 시 대상칼럼으로 groupby됨

In [ ]:
titanic_groupby=titanic_df.groupby(by='Pclass')
print(type(titanic_groupby))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>

대상 칼럼을 제외한 모든 칼럼에 aggregation함수 적용

In [ ]:
titanic_groupby=titanic_df.groupby(by='Pclass').count()
titanic_groupby

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Pclass,,,,,,,,,,,
1,216,216,216,216,186,216,216,216,216,176,214
2,184,184,184,184,173,184,184,184,184,16,184
3,491,491,491,491,355,491,491,491,491,12,491

DataFrameGroupBy객체에 [['passengerId','Survived']]로 필터링해 해당 칼럼에만 count()수행

In [ ]:
titanic_groupby=titanic_df.groupby('Pclass')[['PassengerId','Survived']].count()
titanic_groupby

        PassengerId  Survived
Pclass
1               216       216
2               184       184
3               491       491

서로 다른 agg함수를 적용할 경우 agg() 내에 인자로 입력하여 사용

In [ ]:
titanic_df.groupby('Pclass')['Age'].agg([max,min])

/tmp/ipython-input-414103430.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  titanic_df.groupby('Pclass')['Age'].agg([max,min])
/tmp/ipython-input-414103430.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  titanic_df.groupby('Pclass')['Age'].agg([max,min])

         max   min
Pclass
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

여러개의 칼럼이 서로 다른 agg함수를 적용하려면 딕셔너리 형태로 칼럼과 agg함수 입력

In [ ]:
agg_format={'Age':'max','SibSp':'sum','Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

         Age  SibSp       Fare
Pclass
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

##결손 데이터 처리하기

###isna()로 결손 데이터 여부 확인

NaN이면 True, 아니면 False

In [ ]:
titanic_df.isna().head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False

sum() 호출시 결손 데이터의 개수 구할 수 있음

In [ ]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

###fillna()로 결손 데이터 대체하기

**주의** inplace=True추가하거나 반환 값을 다시 받아야 실제 데이터 세트 값 변경

In [ ]:
titanic_df['Cabin']=titanic_df['Cabin'].fillna('C000')
titanic_df['Cabin'].head(3)

0    C000
1     C85
2    C000
Name: Cabin, dtype: object

In [ ]:
titanic_df['Age']=titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked']=titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

##apply lambda 식으로 데이터 가공

In [ ]:
#lamda 사용하지 않은 경우
def get_square(a):
  return a**2
print('3의 제곱은:',get_square(3))

3의 제곱은: 9

In [ ]:
#lambda 사용
lambda_square=lambda x:x**2
print('3의 제곱은',lambda_square(3))

3의 제곱은 9

In [ ]:
a=[1,2,3]
squares=map(lambda x:x**2,a)
list(squares)

[1, 4, 9]

In [ ]:
titanic_df['Name_len']=titanic_df['Name'].apply(lambda x:len(x))
titanic_df[['Name','Name_len']].head(3)

                                                Name  Name_len
0                            Braund, Mr. Owen Harris        23
1  Cumings, Mrs. John Bradley (Florence Briggs Th...        51
2                             Heikkinen, Miss. Laina        22

In [ ]:
titanic_df['Child_Adult']=titanic_df['Age'].apply(lambda x:'Child' if x<=15 else 'Adult')
titanic_df[['Age','Child_Adult']].head(8)

    Age Child_Adult
0  22.0       Adult
1  38.0       Adult
2  26.0       Adult
3  35.0       Adult
4  35.0       Adult
5   NaN       Adult
6  54.0       Adult
7   2.0       Child

In [ ]:
titanic_df['Age_cat']=titanic_df['Age'].apply(lambda x:'Child' if x<=15 else ('Adult' if x<=60 else 'Elderly'))
titanic_df['Age_cat'].value_counts()

Age_cat
Adult      786
Child       83
Elderly     22
Name: count, dtype: int64

In [ ]:
titanic_df['Age_cat'].head(8)

0      Adult
1      Adult
2      Adult
3      Adult
4      Adult
5    Elderly
6      Adult
7      Child
Name: Age_cat, dtype: object

In [ ]:
def get_category(age):
  cat=''
  if age <=5: cat='Baby'
  elif age <=12: cat='Child'
  elif age <=18: cat='Teenager'
  elif age <=25: cat='Student'
  elif age <=35: cat='Young Adult'
  elif age <=60: cat='Adult'
  else: cat='Senior'
  return cat

titanic_df['Age_cat']=titanic_df['Age'].apply(lambda x:get_category(x))
titanic_df[['Age','Age_cat']].head()

    Age      Age_cat
0  22.0      Student
1  38.0        Adult
2  26.0  Young Adult
3  35.0  Young Adult
4  35.0  Young Adult